// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uyrvbrlkbgaxcesmmlmf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV5cnZicmxrYmdheGNlc21tbG1mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4NTY5NTksImV4cCI6MjA1OTQzMjk1OX0.sEI21pN-YI-mm0_qwoRFpu3ZcRE52WNxUcbTkloqbDc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);